### ISSUE TITLE
TcpVideoStream error: TcpVideoStream timeout after 1000 ms.

### ISSUE THREAD

**Issue by mouhyemen** [felixge/node-ar-drone#124] opened 2015-08-29 13:03 UTC
Despite the patches of #23, I am still facing this trouble. I have the latest node and downloaded the updated library onto my system. Any ideas why the client is not reconnecting and taking care of this?

**Comment by mouhyemen** [comment] 2015-08-30 07:56
So I have made a go at it again. I had node v0.10.33 earlier and now I installed v0.12.7. The client re-connects if it has lost connection and streams in video but the parsing has stopped. In case anyone else faces this problem, try installing to the latest node.

I have checked if TcpVideoStream emits data events after re-connecting and it does. However, the parser has stopped emitting data events.

Has this issue been addressed where once the client loses connection, it is able to reconnect and stream in video from the drone BUT NOT parse it anymore to a h264 file ??

**Comment by wiseman** [comment] 2015-08-30 20:02
I think this is a duplicate of #105.

**Comment by mouhyemen** [comment] 2015-08-31 06:18
Yes it is. I had opened another issue before commenting on #105. Should I close this ?

**Comment by wiseman** [comment] 2015-09-02 15:02
Yes, I'll close this and we'll continue the discussion on #105.  Thanks!

**Closed by wiseman** 2015-09-02 15:02 UTC
