### ISSUE TITLE
 only serves one image after every start-up, and "TcpVideoStream Timeout" error will occur.

### ISSUE THREAD

**Issue by BigRabbit** [felixge/node-ar-drone#119] opened 2015-07-20 14:02 UTC
1.ffmpeg version 
![ffmpeg](https://cloud.githubusercontent.com/assets/1516858/8777410/673d7d7a-2f2a-11e5-9659-8e5696328228.png)
2.TcpVideoStream error
![error](https://cloud.githubusercontent.com/assets/1516858/8777429/881147ac-2f2a-11e5-9e3c-773a9ad0736d.png)
3.run "node test/run.js"
![test](https://cloud.githubusercontent.com/assets/1516858/8777526/0e9ff412-2f2b-11e5-87e6-bba838dfebaa.png)

**Comment by wiseman** [comment] 2015-07-20 17:10
Hi, @BiGrabbit, thanks for the report.  The test failure issue has been reported: See #78 and #49.

The `TcpVideoStream` timeout happens sometimes, but the code is designed to reconnect when that happens, and it looks like that's working as designed in your case.

I'm going to close this for now, but let me know if you don't think I've addressed your issues.

(In the future, please paste text instead of screenshot images--images are not searchable, but text is.)

**Closed by wiseman** 2015-07-20 17:10 UTC

**Comment by BigRabbit** [comment] 2015-07-21 00:54
hello, wiseman! thanks for your reply in time. I want to know how to solve the problem "pngSteram returns only one png after every start-up".

**Comment by wiseman** [comment] 2015-07-21 01:53
Ok, for that issue see #99.
